import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
// import { CounterApp } from "./components/01-useState/CounterApp";
// import { HookApp } from "./HookApp";
// import { CounterWithCustomHook } from "./components/01-useState/CounterWithCustomHook";
// import { SimpleForm } from "./components/02-useEffect/SimpleForm";
// import { FormWithCustom } from "./components/02-useEffect/FormWithCustom";
// import { MultipleCustom } from "./components/03-example/MultipleCustom";
// import FocusScreen from "./components/04-useRef/FocusScreen";
// import RealExampleRef from "./components/04-useRef/RealExampleRef";
// import { Layout } from "./components/05-layoutEffect/LayoutEffect";
// import Memorize from "./components/06-memos/Memorize";
// import MemoHook from "./components/06-memos/MemoHook";
// import CallBackHook from "./components/06-memos/CallBackHook";
// import { Padre } from "./components/07-tarea-memo/Padre";
import TodoApp from "./components/08-useReducer/TodoApp";
// import MainApp from "./components/09-useContext/MainApp";

ReactDOM.render(<TodoApp />, document.getElementById("root"));
